export { Stage } from './stages/stage'
export { Background } from './stages/background'
export { Moon } from './stages/moon'
export { Mountains } from './stages/mountains'
export { Rocks } from './stages/rocks'
export { Water } from './stages/water'